include:
   - project: cells/ci
     file:
        - /ci/lib/tox-bb5.yml
        - /ci/jobs/check-version.yml
        - /ci/jobs/check-packaging.yml
        - /ci/jobs/py37.yml
        - /ci/jobs/py38.yml
        - /ci/jobs/py39.yml
        - /ci/jobs/lint.yml
        - /ci/jobs/docs.yml
        - /ci/jobs/build-package.yml
        - /ci/jobs/publish-package.yml
        - /ci/jobs/publish-docs.yml
        - /ci/jobs/tag.yml
   - project: neuromath/ci
     file:
        - /ci/jobs/auto-release.yml

.tox-template: 
  variables: 
    EXTRA_MODULES: 
        archive/2020-12:neurodamus-neocortex
  before_script:
    - if [[ -z $TOXENV ]]; then echo 'Please set the $TOXENV variable'; exit 1; fi
    - !reference [.define-functions]
    - !reference [.bb5, clean-env]
    - !reference [.bb5, load-python-37]
    - !reference [.bb5, load-extra-modules]
    - !reference [.run-pre-build-command]
    - !reference [.setup-venv]
  
