before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY_BBPCODE" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan bbpcode.epfl.ch >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git config --global user.email "darth@empire.com"
  - git config --global user.name "Darth Vader"

include:
   - project: nse/ci
     file:
        - /ci/lib/tox-bb5.yml
        - /ci/jobs/check-version.yml
        - /ci/jobs/lint.yml
        - /ci/jobs/py36.yml
        - /ci/jobs/py37.yml
        - /ci/jobs/py38.yml
        - /ci/jobs/docs.yml
        - /ci/jobs/build-package.yml
        - /ci/jobs/publish-package.yml
        - /ci/jobs/publish-docs.yml
        - /ci/jobs/tag.yml
   - project: neuromath/ci
     file:
        - /ci/jobs/auto-release.yml