include:
   - project: cells/ci
     file:
        - /ci/lib/tox-bb5.yml
        - /ci/jobs/check-version.yml
        - /ci/jobs/lint.yml
        - /ci/jobs/docs.yml
        - /ci/jobs/build-package.yml


.py-template:
   extends:
      - .tox-template
   before_script:
      - if [[ -z $TOXENV ]]; then echo 'Please set the $TOXENV variable'; exit 1; fi
      - !reference [.define-functions]
      - !reference [.bb5, clean-env]
      - !reference [.bb5, load-python-36]
      - !reference [.bb5, load-python-37]
      - !reference [.bb5, load-python-38]
      - !reference [.bb5, load-extra-modules]
      - !reference [.run-pre-build-command]
      - !reference [.setup-venv]
      - !reference [.gerrit-access]

py36:
   extends: .py-template
   variables:
      TOXENV: py36

py37:
   extends: .py-template
   variables:
      TOXENV: py37

py38:
   extends: .py-template
   variables:
      TOXENV: py38
