before_script:
  # install ssh-agent
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  # run ssh-agent
  - eval $(ssh-agent -s)
  # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  # disable host key checking (NOTE: makes you susceptible to man-in-the-middle attacks)
  # WARNING: use only in docker container, if you use it with shell you will overwrite your user's ssh config
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan bbpcode.epfl.ch >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name "$GITLAB_USER_NAME"


include:
   - project: nse/ci
     file:
        - /ci/lib/tox-bb5.yml
        - /ci/jobs/check-version.yml
        - /ci/jobs/lint.yml
        - /ci/jobs/py36.yml
        - /ci/jobs/py37.yml
        - /ci/jobs/py38.yml
        - /ci/jobs/docs.yml
        - /ci/jobs/build-package.yml
        - /ci/jobs/publish-package.yml
        - /ci/jobs/publish-docs.yml
        - /ci/jobs/tag.yml
   - project: neuromath/ci
     file:
        - /ci/jobs/auto-release.yml
